package com.react.project.Enumirator;

public enum NotificationType {
    // Leave
    LEAVE_REQUEST_SUBMITTED,
    LEAVE_REQUEST_APPROVED,
    LEAVE_REQUEST_REJECTED,
    LEAVE_REQUEST_CANCELLED,
    LEAVE_CANCELLATION_REQUESTED,
    // Schedule
    SCHEDULE_SUBMITTED,
    SCHEDULE_APPROVED,
    SCHEDULE_REJECTED,
    SCHEDULE_UPDATED,
    // Tasks & Projects
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_COMMENTED,
    TASK_DEADLINE_APPROACHING,
    PROJECT_ASSIGNED,
    PROJECT_UPDATED,
    // Team
    TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED,
    // Meetings
    MEETING_SCHEDULED,
    MEETING_UPDATED,
    MEETING_CANCELLED,
    MEETING_REMINDER,
    // Chat
    CHAT_MESSAGE,
    // Performance
    PERFORMANCE_REVIEW,
    // HR
    USER_UPDATED,
    // Generic
    REMINDER,
    ANNOUNCEMENT,
    GENERIC
}
